### PR TITLE
gen_wrap: make sure to put const into function sigs in gen-wrap*.inc

### PR DESCRIPTION
**Pull request by matthiasdiener**
Found while working on #107. Function signatures in gen-wrap*.inc never included the `const` in e.g. `void foo(const char *name){}`.

### CODE REVIEW

**Comment by inducer** [comment]
Why is including the `const` important?

**Comment by inducer** [comment]
Thanks!

**Comment by inducer** [comment]
This is now causing CI failures, e.g. [this](https://github.com/inducer/loopy/actions/runs/5565615240/jobs/10166124008).

**Comment by inducer** [comment]
FWIW, upon looking closer, I do not see why `const` should be included in the wrapper declarators. isl's "take/keep" semantics cover this. Could you explain?

#112 effectively reverts this.

**Comment by matthiasdiener** [comment]
> FWIW, upon looking closer, I do not see why `const` should be included in the wrapper declarators. isl's "take/keep" semantics cover this. Could you explain?
> 
> #112 effectively reverts this.

This was supposed to address the const-related error when building with nanobind (in #107). I think it is less about the take/keep semantics, but more about templating type errors (see https://github.com/inducer/islpy/pull/107#issuecomment-1568478771) when the const-ness doesn't match. I've applied a different workaround in #107 now. 

Sorry for the oversight. 

Should we maybe add a downstream test for pytato in islpy's CI? I can prepare a PR if you like.

**Comment by inducer** [comment]
> Should we maybe add a downstream test for pytato in islpy's CI? I can prepare a PR if you like.

No, I don't think that's necessary. Pytato doesn't use very much isl functionality. Thanks for suggesting it though.

**Pull request merged**
