### PR TITLE
More upcasts

### PR DESCRIPTION
**Pull request by thisiscam**
This PR adds the following upcasts (#78 ):

- pw_aff -> union_pw_aff
- multi_aff -> pw_multi_aff
- pw_multi_aff -> union_pw_multi_aff

and transitive closures of these casts.

The intention is that the upcasts would have the following mirror (between 1. and 2.): 
1. basic_set -> set -> union_set
2. (multi_)aff -> pw_(multi_)aff -> union_pw_(multi_)aff

In particular, I ignored all the aff types where `multi_` is at the leftmost position.

### CODE REVIEW

**Comment by inducer** [comment]
Something seems to be a bit weird with the diff. It seems to contain bits of #66. There are also various merge commits. Could you rebase this onto `main`?

**Comment by inducer** [comment]
No need to close and re-open. You know you can force-push to these, right?

**Comment by thisiscam** [comment]
> You know you can force-push to these, right?

GitHub appended that force push onto its displayed history:

Screen Shot 2021-10-31 at 12 57 15 AM

I guess you are right that from the local git history point of view, I don't need to close-then-reopen. But if I don't know how to tell the difference by this GitHub UI.

**Comment by inducer** [comment]
You get the diff from clicking the link under the words "force-pushed".

**Comment by thisiscam** [comment]
I wasn't aware of that link -- good to know, thanks!
Should we just consider #79 for now? It would be a hassle to close it and rework on this one, and that one is strictly cleaner :)

**Pull request closed without merging**
